security:
  secret:
    key: "25ea99c20638c1fbdcaaa55f30d2a5222d60307de871d6c8d03395f785a31cdf"

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3305/service?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

yolo:
  api:
    url: http://localhost:5000/v1/object-detection/yolov5
