security:
  secret:
    key: "25ea99c20638c1fbdcaaa55f30d2a5222d60307de871d6c8d03395f785a31cdf"

spring:
#  profiles:
#    active: test

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://mariadb-container:3306/service?characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mariadb://localhost:3306/service?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  server:
    address: 0.0.0.0
    port: 8080