spring:
  datasource:
    url: jdbc:h2:mem:testdb  # H2 메모리 데이터베이스 사용
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update  # 자동으로 스키마 생성
  h2:
    console:
      enabled: true  # H2 콘솔 활성화 (옵션)
