name: Build and Deploy YOLO Docker Image

on:
  push:
    branches:
      - main
      - yolo
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 60  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Debug Docker Build
      run: |
        docker buildx build --no-cache -t ${{ secrets.YOLO_DOCKER_USERNAME }}/yolo-image:latest ./yolo
        docker images
  
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.YOLO_DOCKER_USERNAME }}
        password: ${{ secrets.YOLO_DOCKERHUB_TOKEN }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.YOLO_DOCKER_USERNAME }}/yolo-image:latest || true
        docker images