name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - yolo
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # 타임아웃을 60분으로 설정

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.YOLO_DOCKER_USERNAME }}
        password: ${{ secrets.YOLO_DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image (without cache)
      run: |
        docker buildx build --no-cache -t ${{ secrets.YOLO_DOCKER_USERNAME }}/yolo-image:latest ./yolo
        docker push ${{ secrets.YOLO_DOCKER_USERNAME }}/yolo-image:latest

    - name: Verify Docker image
      run: |
        docker pull ${{ secrets.YOLO_DOCKER_USERNAME }}/yolo-image:latest
        docker images
