name: Build and Deploy Spring Docker Image

on:
  push:
    branches:
      - main 
      - spring

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 레포지토리 클론
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Change to APIService directory
      - name: Change to APIService directory
        run: cd APIService

      # 3. Java 환경 설정
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 4. Gradle 빌드
      - name: Build JAR with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      # 5. Docker 이미지 빌드
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.SPRING_DOCKER_USERNAME }}/spring-api:latest .

      # 6. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.SPRING_DOCKER_USERNAME }}
          password: ${{ secrets.SPRING_DOCKERHUB_TOKEN }}

      # 7. Docker 이미지 푸시
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.SPRING_DOCKER_USERNAME }}/spring-api:latest
